### PR TITLE
Auth 101 

### PR DESCRIPTION
**Pull request by chris-githu**
TODO
_Document what's changed here_

### CODE REVIEW

**Comment by chris-githu** [comment]
@drjavanew @ojuolarpe 
Please take note of the updated SecurityConfig
```
http.sessionManagement().sessionCreationPolicy(SessionCreationPolicy.STATELESS)
                .and()
                    .authorizeRequests()
                    .antMatchers("/api/authenticate").permitAll()
                    .antMatchers("/api/**").authenticated()
```
upon deployment, all endpoints except `/authenticate` with require authentication

**Comment by ojuolarpe** [comment]
@chris-githu This is good to go, but there's a merge conflict. Can you resolve this conflict?

**Comment by ojuolarpe** [comment]
@drjavanew Lets adopt the pagination implementation in the "Get All Users endpoint" for all the "fetch All" APIs.

**Comment by chris-githu** [comment]
@ojuolarpe Resolved

**Pull request merged**
